version: "3.3"

services:
  backend:
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8087:8000"
    command: gunicorn --bind 0.0.0.0:8000 store.wsgi
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  media:
